# coding=utf-8
import turtle

# 设置画布和画笔
screen = turtle.Screen()
screen.setup(800, 600)
screen.bgcolor("#000")
turtle.pensize(2)

# 绘制头部和眼睛
turtle.penup()
turtle.goto(0, 200)
turtle.pendown()
turtle.fillcolor("#c1272d")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(-40, 240)
turtle.pendown()
turtle.fillcolor("#fff")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 240)
turtle.pendown()
turtle.fillcolor("#fff")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

# 绘制嘴巴
turtle.penup()
turtle.goto(-60, 180)
turtle.pendown()
turtle.right(20)
turtle.circle(100, 40)
turtle.left(30)
turtle.circle(40, 180)
turtle.left(30)
turtle.circle(100, 40)

# 绘制身体
turtle.penup()
turtle.goto(-120, -50)
turtle.pendown()
turtle.fillcolor("#d9d9d9")
turtle.begin_fill()
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(120)
turtle.right(60)
turtle.forward(60)
turtle.right(120)
turtle.forward(120)
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(120)
turtle.right(60)
turtle.forward(60)
turtle.right(120)
turtle.forward(120)
turtle.end_fill()

# 绘制手臂和手
turtle.penup()
turtle.goto(-200, 50)
turtle.pendown()
turtle.fillcolor("#c1272d")
turtle.begin_fill()
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(120)
turtle.right(60)
turtle.forward(60)
turtle.right(120)
turtle.forward(120)
turtle.end_fill()
turtle.penup()
turtle.goto(80, 50)
turtle.pendown()
turtle.fillcolor("#c1272d")
turtle.begin_fill()
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(120)
turtle.left(60)
turtle.forward(60)
turtle.left(120)
turtle.forward(120)
turtle.end_fill()

# 绘制腿和脚
turtle.penup()
turtle.goto(-100, -200)
turtle.pendown()
turtle.fillcolor("#d9d9d9")
turtle.begin_fill()
turtle.right(60)
turtle.forward(60)
turtle.right(60)
turtle.forward(120)
turtle.right(60)
turtle.forward(60)
turtle.right(120)
turtle.forward(120)
turtle.end_fill()
turtle.penup()
turtle.goto(20, -200)
turtle.pendown()
turtle.fillcolor("#d9d9d9")
turtle.begin_fill()
turtle.left(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(120)
turtle.left(60)
turtle.forward(60)
turtle.left(120)
turtle.forward(120)
turtle.end_fill()

# 绘制细节和阴影
turtle.penup()
turtle.goto(0, 160)
turtle.pendown()
turtle.pensize(4)
turtle.pencolor("#fff")
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.goto(0, 140)
turtle.pendown()
turtle.pencolor("#c1272d")
turtle.circle(30)
turtle.penup()
turtle.goto(-120, -50)
turtle.pendown()
turtle.pencolor("#c1272d")
turtle.forward(60)
turtle.penup()
turtle.goto(120, -50)
turtle.pendown()
turtle.pencolor("#c1272d")
turtle.forward(60)
turtle.penup()
turtle.goto(-40, 100)
turtle.pendown()
turtle.pencolor("#fff")
turtle.fillcolor("#fff")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-80, 0)
turtle.pendown()
turtle.fillcolor("#000")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(80, 0)
turtle.pendown()
turtle.fillcolor("#000")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-100, -220)
turtle.pendown()
turtle.fillcolor("#000")
turtle.begin_fill()
turtle.right(60)
turtle.forward(20)
turtle.right(60)
turtle.forward(40)
turtle.right(60)
turtle.forward(20)
turtle.right(120)
turtle.forward(40)
turtle.end_fill()
turtle.penup()
turtle.goto(20, -220)
turtle.pendown()
turtle.fillcolor("#000")
turtle.begin_fill()
turtle.left(60)
turtle.forward(20)
turtle.left(60)
turtle.forward(40)
turtle.left(60)
turtle.forward(20)
turtle.left(120)
turtle.forward(40)
turtle.end_fill()

turtle.hideturtle()

turtle.done()
